test-name: train-data
ocr-system: paddleocr
augmentation: True
augmentation-config:
    blur:
        blur_limit: 7
        p: 1.0
    brightness:
        p: 0.5

# draw settings
draw-process:
    color: [0, 0, 0]
    thickness: 1

# task to execute
tasks:
    det: y
    rec: y

# dictionary to use and number of workers
dict: ./dict/en_dict.txt
workers: 8

# list of dataset to select
datasets:
    TLT_3060_Faz1_Dataset: y
    cord:
    funsd: y
    gnhk:
    iam:
    sroie:
    xfund:
        xfund-de:
        xfund-es:
        xfund-fr:
        xfund-it:
        xfund-ja:
        xfund-pt:
        xfund-zh:
    wildreceipt: